version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: version_control
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8088:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/version_control
